### ISSUE TITLE
Inputs of Translation Averaging Need Absolute Rotation of Each View and Relative Pose of Piar Views

### ISSUE THREAD

**Issue by qingchenwuhou** [AIBluefisher/GraphOptim#6]
Hi, 
Thanks your great work!
There is a bug in your code:
Description:
    Inputs of Translation Averaging Need Absolute Rotation of Each View and Relative Pose of View Pair , 
    But in examples/position_estimator.cc: 56 view_graph.ReadG2OFile(g2o_filename);
    you only convey relative rotation and relative translation. 

So, the following codes need to be corrected:

edge.cc:  
    replace :
  // node_t src = kInvalidNodeId;
  // node_t dst = kInvalidNodeId;
    with: 
  ImageNode src;
  ImageNode dst;
  and correct construction fun correspondingly,
view_graph.cc: 
    ViewGraph::ReadG2OFile, add absolute rotation to edge.src and edge.dst.
graph.inl:
  correct AddEdge and AddNodes etc.
and some test functions.

**Comment by AIBluefisher** [comment]
Note (1) the edge only contains the node indices in order to save memory. (2) In a view graph, (given indices) we are able to access nodes directly, and consequently, the absolute rotations hold by the corresponding nodes. (You can refer to the translation averaging part: https://github.com/AIBluefisher/GraphOptim/blob/main/src/graph/view_graph.cc.) (3) thus the absolute rotations required by translation averaging can be accessed by the existing interface.

I won't make any modifications to the interface if there is no solid reason. But I'd like to add the test function to the translation averaging method.

Hope this answered your question.

**Comment by qingchenwuhou** [comment]
OK，thanks for your reply.



发自我的iPhone


------------------ Original ------------------
From: Chenyu ***@***.***&gt;
Date: Tue,Mar 1,2022 10:13 PM
To: AIBluefisher/GraphOptim ***@***.***&gt;
Cc: YangDuoDuo ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [AIBluefisher/GraphOptim] Inputs of Translation Averaging Need Absolute Rotation of Each View and Relative Pose of Piar Views (Issue #6)





 
Note (1) the edge only contains the node indices in order to save memory. (2) In a view graph, (given indices) we are able to access nodes directly, and consequently, the absolute rotations hold by the corresponding nodes. (You can refer to the translation averaging part: https://github.com/AIBluefisher/GraphOptim/blob/main/src/graph/view_graph.cc.) (3) thus the absolute rotations required by translation averaging can be accessed by the existing interface.
 
I won't make any modifications to the interface if there is no solid reason. But I'd like to add the test function to the translation averaging method.
 
Hope this answered your question.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
